config/routes.rb
AlbumSample::Application.routes.draw do

  resources :users
  resources :albums, :only => [ :new]
  resources :images, :only => [ :new, :index]

  root :to => 'users#index'

end

app/models/album.rb
class Album < ActiveRecord::Base
  attr_accessible :name, :images_attributes
  belongs_to  :user
  has_many    :images

  accepts_nested_attributes_for :images,
    :reject_if => lambda { |e| (e[:photo].blank? && e[:description].blank? && e[:tag_list].blank?)},
    :allow_destroy => true

end

app/models/image.rb
class Image < ActiveRecord::Base
  attr_accessible :description, :photo, :tag_list
  attr_accessor :tag_list

  belongs_to :album
  has_and_belongs_to_many :tags

  has_attached_file :photo, :styles => { :thumb => "100x100>", :medium => "250x250>"  }
  validates :photo, :attachment_presence => true

  before_save :ensure_tags

  def tag_list
    @tag_list || tags.collect(&:name)
  end

  def tag_list=( _list)
    @tag_list = _list.split(",").collect(&:strip).flatten.compact.uniq
    ensure_tags
  end

  def tag_names
    tag_list.join(", ")
  end

  private
  def ensure_tags
    if( @tag_list.present? )
      self.tags = tag_list.collect{ |e| Tag.find_or_create_by_name( e)}
    end
  end

end

app/models/tag.rb
class Tag < ActiveRecord::Base
  attr_accessible :name

  has_and_belongs_to_many :images

  validates :name, presence: true, uniqueness: true
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :albums_attributes

  has_many :albums

  accepts_nested_attributes_for :albums, allow_destroy: true

end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

  def new
    @album = Album.new
    @album.images.build
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController

  def new
    @image        = Image.new
    @album_number = params[:album]
  end

  def index
    _tag = Tag.find_by_name( params[:tag])
    @images = _tag.try(:images)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def new
    @user = User.new
    @user.albums.build
    @user.albums.first.images.build
  end

  def create
    @user = User.new( params[:user])

    if( @user.save)
      redirect_to( @user, notice: 'User and associated Albums created successfully')
    else
      render( action: 'new')
    end
  end

  def update
    @user = User.find( params[:id])

    if( @user.update_attributes( params[:user]))
      redirect_to( @user, notice: 'User and associated Albums updated successfully')
    else
      render( action: 'edit')
    end
  end

  def show
    @user = User.find( params[:id])
  end

  def edit
    @user = User.find( params[:id])
  end

  def destroy
    @user = User.find( params[:id])
    @user.destroy
    redirect_to users_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/albums/_album.html.erb
<div class='table-bordered'>
  <% _num = album.id.blank? ? rand(1000000) : album.id %>
 <div id='album-<%= _num %>' class='album'>
  <%= fields_for "user[albums_attributes][#{ _num}]", album do |f| %>
    <div class="form-inline">
      <%= f.label :name, 'Album name'%>
      <%= f.text_field :name %>
    </div>
    <div class='row'>&nbsp;</div>
    <%= f.hidden_field :id %>
    <%= f.hidden_field :_destroy, value: false, class: 'destroy' %>

    <%= render( partial: 'users/image', collection: album.images, locals: { num: _num})%>
  <%  end -%>
 </div>

  <%= link_to_function 'Remove Album', 'remove_element(this)', class: 'btn icon-remove pull-right btn-danger' %>
  <%= link_to 'Add Image', new_image_path( album: _num), remote: true, class: 'btn icon-plus btn-small pull-right btn-primary' %>
  <div class='row'>&nbsp;</div>
  <div class='row'>&nbsp;</div>
</div>

app/views/albums/new.js.erb
$('#albums').append( "<%=j render( :partial => 'users/album', :object => @album) %>")

app/views/images/_image.html.erb
<div class="well well-samll">
  <%=image_tag image.photo.url( :medium), class: "img-polaroid" %>
  <strong class="label label-info">Description: </strong> <%= image.description %>
  <p>
    <strong class="label label-info">Tags: </strong>
    <% image.tag_list.each do |_tag|%>
      <span class="label label-important"> <%= link_to( _tag, images_path( :tag => _tag)) %></span>
    <% end %>
  </p>
</div>

app/views/images/index.html.erb
<h4> Images </h4>
<%= @images.present? ? render( partial: :image, collection: @images) : "no image exists " %>

<%= link_to( 'back', users_path, class: 'btn') %>

app/views/images/new.js.erb
$('#album-<%= @album_number %>').append( "<%=j render( :partial => 'users/image', :object => @image, locals: { num: @album_number}) %>")

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AlbumSample</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class='container'>
    <div class='row'>
      <div class='span12'>
        <%= yield %>
      </div>
    </div>
  </div>
</body>
</html>

app/views/users/_album.html.erb
<div class='table-bordered'>
  <% _num = album.id.blank? ? rand(1000000) : album.id %>
 <div id='album-<%= _num %>' class='album'>
  <%= fields_for "user[albums_attributes][#{ _num}]", album do |f| %>
    <div class="form-inline">
      <%= f.label :name, 'Album name'%>
      <%= f.text_field :name %>
    </div>
    <div class='row'>&nbsp;</div>
    <%= f.hidden_field :id %>
    <%= f.hidden_field :_destroy, value: false, class: 'destroy' %>

    <%= render( partial: 'users/image', collection: album.images, locals: { num: _num})%>
  <%  end -%>
 </div>

  <%= link_to_function 'Remove Album', 'remove_element(this)', class: 'btn icon-remove pull-right btn-danger' %>
  <%= link_to 'Add Image', new_image_path( album: _num), remote: true, class: 'btn icon-plus btn-small pull-right btn-primary' %>
  <div class='row'>&nbsp;</div>
  <div class='row'>&nbsp;</div>
</div>

app/views/users/_form.html.erb
<%= form_for(@user, :html => {:multipart => true, :class => "table-bordered"}) do |f| %>

  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-inline">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class='row'>&nbsp;</div>
  <div id="albums" class='table-bordered'>
    <%= render( partial: 'album', collection: @user.albums) %>
  </div>
  <%= link_to 'Add Album', new_album_path, remote: true, class: 'btn btn-small icon-plus btn-primary' %>
  <div class='row'>&nbsp;</div>
  <%= f.submit :class => 'btn-primary btn-large'%>
<% end %>

app/views/users/_image.html.erb
<div class='image form-inline table-bordered'>
  <%= fields_for "user[albums_attributes][#{ num}][images_attributes][#{rand( 10000000)}]", image do |img| %>
    <%= image_tag( img.object.photo.url( :thumb), class: "img-polaroid") unless img.object.new_record? %>
    <%= img.file_field( :photo) %>
    <%= img.label :description %>
    <%= img.text_area :description, rows: 2 %>
    <%= img.label :tag_list %>
    <%= img.text_area :tag_list, rows: 2 , :value => img.object.tag_names %>
    <%= img.hidden_field :id %>
    <%= img.hidden_field :_destroy, value: false, class: 'destroy' %>

  <% end -%>
  <%= link_to_function 'Remove Image', 'remove_element(this)', class: 'btn  icon-minus btn-small btn-danger' %>
</div>

app/views/users/edit.html.erb
<h4> Editing user details</h4>

<%= render( partial: 'form') %>

<hr>
<%= link_to 'back to all users', users_path %> | <%= link_to 'show user', user_path( @user), class: 'icon-user' %>

app/views/users/index.html.erb
<div class='row'>
  &nbsp;
</div>

<table class='table table-hover'>
  <caption><h3> Users list</h3> </caption>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |_usr| %>
      <tr>
        <td> <%= _usr.name %> </td>
        <td> <%= link_to 'Show', user_path( _usr), :class => 'btn btn-small icon-user' %>
             <%= link_to 'Edit', edit_user_path( _usr), :class => 'btn btn-small icon-pencil' %>
              <%= link_to 'Destroy', user_path( _usr), method: :delete, :confirm => 'Are you sure?', :class => 'btn btn-danger btn-small icon-trash' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<hr>
<%= link_to 'Add new user', new_user_path, :class => 'btn btn-primary btn-large icon-user'%>

app/views/users/new.html.erb
<h4>New User Details</h4>

<%= render( :partial => 'form')%>

<%= link_to 'back to all users', users_path %>

app/views/users/show.html.erb
<div class="table-bordered">
  <h3>User details</h3>
  <div class="table-bordered">
    Name: <%= @user.name %>
    <div class='row'> &nbsp;</div>
    <div class="table-bordered">
      <h6>Albums</h6>
      <% @user.albums.each do |_album| %>
        <div class="well well-small">
          <p> Album Name: <%= _album.name %> </p>

          <%= render partial: 'images/image', collection: _album.images %>
        </div>
      <% end -%>

    </div>
  </div>
</div>

<%= link_to 'back to all users', users_path %> |
<%= link_to 'edit user', edit_user_path( @user), class: "icon-user"%>